"""Compatibility facade for Lumen SQLAlchemy models.

Canonical entity definitions live in :mod:`lumen_core.model_entities`.  This
module preserves the historical ``lumen_core.models`` import surface and loads
canvas entities so ``Base.metadata`` remains complete for Alembic and tests.
"""

from __future__ import annotations

from .memory_extraction_models import MemoryExtractionRun
from .model_base import (  # noqa: F401 - compatibility re-exports
    Base,
    SoftDeleteMixin,
    TimestampMixin,
    new_uuid7,
)
from .model_entities import (  # noqa: F401 - compatibility re-exports
    USER_API_CREDENTIAL_STATUSES,
    User,
    AllowedEmail,
    AuthSession,
    SystemPrompt,
    ApiSupplierTemplate,
    UserApiCredential,
    PendingApiKeyVerification,
    Conversation,
    Message,
    UserMemoryScope,
    UserMemory,
    UserMemoryStaging,
    MemoryAudit,
    Generation,
    Completion,
    VideoGeneration,
    Image,
    Video,
    ImageVariant,
    WorkflowRun,
    WorkflowStep,
    ModelCandidate,
    QualityReport,
    Share,
    OutboxEvent,
    UserWallet,
    WalletTransaction,
    BillingWindowUsageEvent,
    PricingRule,
    RedemptionBatch,
    RedemptionCode,
    RedemptionCodeUsage,
    InviteLink,
    SystemSetting,
    AuditLog,
    TelegramBinding,
    ModelLibraryItem,
    ModelLibraryHiddenPreset,
    PosterStyleItem,
    PosterStyleHiddenPreset,
    PosterMaster,
    PosterRender,
    OutboxDeadLetter,
)

from . import canvas_models as _canvas_models  # noqa: F401

__all__ = [
    "Base",
    "User",
    "AllowedEmail",
    "AuthSession",
    "SystemPrompt",
    "Conversation",
    "Message",
    "UserMemoryScope",
    "UserMemory",
    "UserMemoryStaging",
    "MemoryAudit",
    "MemoryExtractionRun",
    "Generation",
    "Completion",
    "Image",
    "ImageVariant",
    "WorkflowRun",
    "WorkflowStep",
    "ModelCandidate",
    "ModelLibraryItem",
    "ModelLibraryHiddenPreset",
    "PosterStyleItem",
    "PosterStyleHiddenPreset",
    "PosterMaster",
    "PosterRender",
    "QualityReport",
    "Share",
    "OutboxEvent",
    "InviteLink",
    "SystemSetting",
    "AuditLog",
    "OutboxDeadLetter",
    "TelegramBinding",
    "ApiSupplierTemplate",
    "UserApiCredential",
    "PendingApiKeyVerification",
    "USER_API_CREDENTIAL_STATUSES",
    "new_uuid7",
]
