"""Thin model-library workflow route compatibility module."""

from __future__ import annotations

from ...workflow_services import model_library_endpoints as _impl


router = _impl.router
FACADE_EXPORTS = _impl.FACADE_EXPORTS

_MODEL_LIBRARY_TITLE_AGE_LABELS = _impl.MODEL_LIBRARY_TITLE_AGE_LABELS
_model_library_generate_genders = _impl.model_library_generate_genders
_model_library_gender_label = _impl.model_library_gender_label
_model_library_run_title = _impl.model_library_run_title
_model_library_generate_prompt = _impl.model_library_generate_prompt
_model_library_generate_image_params = _impl.model_library_generate_image_params
_model_library_run_inputs = _impl.model_library_run_inputs
_saved_image_id_set = _impl.saved_image_id_set
_model_library_job_status = _impl.model_library_job_status
_gather_job_image_outs = _impl.gather_job_image_outs
_model_library_image_meta_by_id = _impl.model_library_image_meta_by_id
_job_item_out = _impl.job_item_out
_extract_bonus_ids = _impl.extract_bonus_ids
_workflow_produced_model_image_ids = _impl.workflow_produced_model_image_ids
_job_from_library_run = _impl.job_from_library_run
_job_from_project_candidate_step = _impl.job_from_project_candidate_step
_enqueue_model_library_generate_tasks = _impl.enqueue_model_library_generate_tasks
_model_library_explicit_genders = _impl.model_library_explicit_genders
_reference_profile_has_required_text_fields = (
    _impl.reference_profile_has_required_text_fields
)
_merge_reference_overrides = _impl.merge_reference_overrides
generate_apparel_model_library_job = _impl.generate_apparel_model_library_job
list_apparel_model_library_jobs = _impl.list_apparel_model_library_jobs
delete_apparel_model_library_job = _impl.delete_apparel_model_library_job
clear_apparel_model_library_jobs = _impl.clear_apparel_model_library_jobs
save_apparel_model_library_job_item = _impl.save_apparel_model_library_job_item
_api_call_tagging_upstream = _impl.api_call_tagging_upstream
_AGE_ALIASES_API = _impl.AGE_ALIASES_API
_normalize_tagged_age = _impl.normalize_tagged_age
_normalize_tagged_gender = _impl.normalize_tagged_gender
_auto_tag_library_item = _impl.auto_tag_library_item
_run_auto_tag_in_background = _impl.run_auto_tag_in_background
auto_tag_apparel_model_library_item = _impl.auto_tag_apparel_model_library_item


__all__ = [*FACADE_EXPORTS, "FACADE_EXPORTS", "router"]


# Public compatibility contracts.
AGE_ALIASES_API = _AGE_ALIASES_API
MODEL_LIBRARY_TITLE_AGE_LABELS = _MODEL_LIBRARY_TITLE_AGE_LABELS
api_call_tagging_upstream = _api_call_tagging_upstream
auto_tag_library_item = _auto_tag_library_item
enqueue_model_library_generate_tasks = _enqueue_model_library_generate_tasks
extract_bonus_ids = _extract_bonus_ids
gather_job_image_outs = _gather_job_image_outs
job_from_library_run = _job_from_library_run
job_from_project_candidate_step = _job_from_project_candidate_step
job_item_out = _job_item_out
merge_reference_overrides = _merge_reference_overrides
model_library_explicit_genders = _model_library_explicit_genders
model_library_gender_label = _model_library_gender_label
model_library_generate_genders = _model_library_generate_genders
model_library_generate_image_params = _model_library_generate_image_params
model_library_generate_prompt = _model_library_generate_prompt
model_library_image_meta_by_id = _model_library_image_meta_by_id
model_library_job_status = _model_library_job_status
model_library_run_inputs = _model_library_run_inputs
model_library_run_title = _model_library_run_title
normalize_tagged_age = _normalize_tagged_age
normalize_tagged_gender = _normalize_tagged_gender
reference_profile_has_required_text_fields = _reference_profile_has_required_text_fields
run_auto_tag_in_background = _run_auto_tag_in_background
saved_image_id_set = _saved_image_id_set
workflow_produced_model_image_ids = _workflow_produced_model_image_ids
